from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from grok_service import question_to_sql
from db_service import execute_query
import httpx
import psycopg2

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8080"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def root():
    return {"status": "Backend is running"}

@app.post("/api/query")
def query(data: dict):
    question = data.get("question", "")

    if not question:
        return {"error": "No question provided"}

    try:
        sql = question_to_sql(question)
    except httpx.TimeoutException:
        return {"error": "Grok AI took too long to respond"}
    except httpx.ConnectError:
        return {"error": "Could not connect to Grok AI API"}
    except httpx.HTTPStatusError as e:
        return {"error": f"Grok AI returned error {e.response.status_code}"}
    except Exception as e:
        return {"error": f"Unexpected Grok AI error: {str(e)}"}

    try:
        results = execute_query(sql)
    except psycopg2.OperationalError:
        return {"error": "Could not connect to the database", "sql": sql}
    except psycopg2.ProgrammingError as e:
        return {"error": f"Invalid SQL generated by AI: {str(e)}", "sql": sql}
    except psycopg2.Error as e:
        return {"error": f"Database error: {str(e)}", "sql": sql}
    except Exception as e:
        return {"error": f"Unexpected database error: {str(e)}", "sql": sql}

    return {
        "question": question,
        "sql": sql,
        "results": results
    }